name: Monitor Intune Endpoint Lists

on:
  workflow_dispatch:
  schedule:
    # Daily at 07:00 AM US‑Eastern (11:00 UTC)
    - cron: '0 11 * * *'

permissions:
  contents: write

jobs:
  check-endpoints:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

    steps:
      # 0) Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 1) Install jq and (if necessary) PowerShell Core
      - name: Install jq & PowerShell
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y jq
          if ! command -v pwsh &>/dev/null; then
            echo "Installing PowerShell Core…"
            sudo apt-get install -y wget apt-transport-https software-properties-common
            wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update -y
            sudo apt-get install -y powershell
          fi

      # 2) Generate current endpoint list
      - name: Generate endpoint list
        id: generate
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $json = Invoke-RestMethod -Uri ("https://endpoints.office.com/endpoints/WorldWide?ServiceAreas=MEM&clientrequestid=$([guid]::NewGuid())")
          $ips  = $json | Where-Object { $_.ServiceArea -eq 'MEM' -and $_.ips  } | Select-Object -ExpandProperty ips  -Unique
          $urls = $json | Where-Object { $_.ServiceArea -eq 'MEM' -and $_.urls } | Select-Object -ExpandProperty urls -Unique
          $payload = [pscustomobject]@{
            timestamp = (Get-Date).ToString('o')
            ip_count  = $ips.Count
            url_count = $urls.Count
            ips       = $ips  | Sort-Object
            urls      = $urls | Sort-Object
          }
          $payload | ConvertTo-Json -Depth 5 | Set-Content endpoints.json -Encoding utf8

      # 3) Detect meaningful changes (ignore timestamp line)
      - name: Detect changes (ignore timestamp)
        id: changes
        run: |
          set -e
          grep -v '"timestamp"' endpoints.json > new.json
          if git show HEAD:endpoints.json > old_raw.json 2>/dev/null; then
            grep -v '"timestamp"' old_raw.json > old.json
          else
            touch old.json
          fi
          if cmp -s old.json new.json; then
            echo "changed=no" >> $GITHUB_OUTPUT
          else
            echo "changed=yes" >> $GITHUB_OUTPUT
          fi

      # 4) Commit & push when changed
      - name: Commit updated list
        if: steps.changes.outputs.changed == 'yes'
        run: |
          set -e
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add endpoints.json
          git commit -m "chore(intune): update endpoints $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || exit 0
          git push origin HEAD:${GITHUB_REF#refs/heads/}

      # 5) Capture diffs for notifications
      - name: Capture diff
        if: steps.changes.outputs.changed == 'yes'
        id: diff
        run: |
          set -e
          FULL_DIFF=$(git show --pretty=medium --unified=5 --no-color HEAD)
          DISCORD_DIFF=$(echo "$FULL_DIFF" | head -n 60)
          if [ ${#DISCORD_DIFF} -gt 1800 ]; then
            DISCORD_DIFF=$(git diff --shortstat HEAD~1 HEAD)
          fi
          echo "FULL_DIFF<<EOF" >> $GITHUB_ENV
          echo "$FULL_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DISCORD_DIFF<<EOF" >> $GITHUB_ENV
          echo "$DISCORD_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # 6) Send notifications
      - name: Send notifications
        if: steps.changes.outputs.changed == 'yes'
        env:
          FULL_DIFF: ${{ env.FULL_DIFF }}
          DISCORD_DIFF: ${{ env.DISCORD_DIFF }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          set -e
          post_slack() {
            jq -n --arg text "ℹ️ *Intune Endpoint Update* (<${COMMIT_URL}|commit>)\n```diff\n${FULL_DIFF}\n```" '{text:$text}' | \
              curl -sS -X POST -H 'Content-Type: application/json' --data @- "$SLACK_WEBHOOK_URL"
          }
          post_discord() {
            jq -n --arg content "**Intune Endpoint Update**\n${COMMIT_URL}\n```diff\n${DISCORD_DIFF}\n```" '{content:$content}' | \
              curl -sS -X POST -H 'Content-Type: application/json' --data @- "$DISCORD_WEBHOOK_URL"
          }
          post_datadog() {
            curl -sS -X POST "https://api.datadoghq.com/api/v1/events" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: $DATADOG_API_KEY" \
              -d "{\"title\":\"Intune endpoints changed\",\"text\":\"See commit: ${COMMIT_URL}\",\"alert_type\":\"info\",\"tags\":[\"intune\",\"endpoints\"]}"
          }
          [ -n "$SLACK_WEBHOOK_URL" ]   && post_slack   || echo "Slack not configured – skipping"
          [ -n "$DISCORD_WEBHOOK_URL" ] && post_discord || echo "Discord not configured – skipping"
          [ -n "$DATADOG_API_KEY" ]     && post_datadog || echo "Datadog not configured – skipping"